export const GET_POKEMON_REQUEST = "GET_POKEMON_REQUEST";
export const GET_POKEMON_SUCCESS = "GET_POKEMON_SUCCESS";
export const GET_POKEMON_FAIL = "GET_POKEMON_FAIL";

export const TEAM_ADD_POKEMON = "TEAM_ADD_POKEMON";
export const TEAM_REMOVE_POKEMON = "TEAM_REMOVE_POKEMON";

export const GET_ALL_POKEMON_REQUEST = "GET_ALL_POKEMON_REQUEST";
export const GET_ALL_POKEMON_SUCCESS = "GET_ALL_POKEMON_SUCCESS";
export const GET_ALL_POKEMON_FAIL = "GET_ALL_POKEMON_FAIL";
